# Generated by Django 4.2.16 on 2024-11-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='flowers_img/'),
        ),
    ]
